example.property= I AM DEV

# DataSource settings: set here your own configurations for the database
spring.datasource.url = jdbc:postgresql://:5432/ostock_dev
spring.datasource.username = postgres
spring.datasource.password ={cipher}d93b85fdc49651597c8bea0272c98f7351f96ed93f074cab6fe72565b5cb0701