spring.datasource.url=jdbc:postgresql://db:5432/ostock_dev
spring.datasource.username=postgres
spring.datasource.password={cipher}d93b85fdc49651597c8bea0272c98f7351f96ed93f074cab6fe72565b5cb0701
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none

example.property=I AM THE DOCKER!

eureka.client.serviceUrl.defaultZone=http://eureka-server:8070/eureka/
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
eureka.instance.status-page-url-path=/actuator/info
eureka.instance.health-check-url-path=/actuator/health
eureka.instance.home-page-url-path=/

logging.level.root=DEBUG