example.property= I AM THE DEFAULT from organization

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql = true
spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/ostock_dev
spring.datasource.username=postgres
spring.datasource.password=example
spring.datasource.driver-class-name=org.postgresql.Driver
spring.database.driverClassName= org.postgresql.Driver
spring.datasource.testWhileIdle = true
spring.datasource.validationQuery = SELECT 1
spring.datasource.platform=postgres

management.endpoints.web.exposure.include=*
management.endpoints.enabled-by-default=true

# ????????? Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8070/eureka/
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.instance.non-secure-port=${server.port}
eureka.instance.status-page-url-path=/actuator/info
eureka.instance.health-check-url-path=/actuator/health
eureka.instance.home-page-url-path=/

feign.client.config.organization-service.connectTimeout=5000
feign.client.config.organization-service.readTimeout=5000